services:
  nextjs-app:
    container_name: seekhcode-www
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "server.js"]
    ports:
      - '3000:3000'  
    volumes:
      - .:/app
      - /app/node_modules  