services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "server.js"]
    ports:
      - '3000:3000'  
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules  

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - '8432:5432' 
    volumes:
      - pgdata:/var/lib/postgresql/data  

volumes:
  pgdata:
    driver: local
